#!/usr/bin/env bash
# Rename the project: leash -> wardyn.
# Run from the repo ROOT, on a machine that can `cargo build` (your Linux VM).
# This edits files + moves dirs but verifies nothing — you MUST build after.
#
#   git fetch && git checkout chore/public-readiness
#   bash rename-to-wardyn.sh
#   cargo build && cargo test -p wardyn      # <-- the real gate
#   git add -A && git commit -m "chore: rebrand leash -> wardyn"
#   git push
set -euo pipefail

# 1) directories (specific names first; git mv keeps history)
git mv leash-common wardyn-common
git mv leash-ebpf   wardyn-ebpf
git mv leash        wardyn

# 2) content — specific tokens BEFORE the bare word (order matters).
#    LICENSE (verbatim AGPL) is never touched; Cargo.lock is deleted below and
#    regenerated by cargo, so it isn't sed-ed here.
mapfile -t files < <(git ls-files -- '*.rs' '*.toml' '*.md' '*.yml' '*.yaml' '*.sh' 'justfile')
for f in "${files[@]}"; do
  sed -i \
    -e 's/leash-common/wardyn-common/g' \
    -e 's/leash-ebpf/wardyn-ebpf/g' \
    -e 's/leash_common/wardyn_common/g' \
    -e 's/leash-audit/wardyn-audit/g' \
    -e 's/\bleash\b/wardyn/g' \
    "$f"
done

# 3) Cargo.lock: drop it, cargo regenerates a correct one on the next build.
rm -f Cargo.lock

echo
echo "== NEXT =="
echo "  cargo build && cargo test -p wardyn     # must pass — this is the verification"
echo
echo "  Then read these two spots by eye (blind sed can't judge prose):"
echo "   - README.md / ARCHITECTURE.md tagline: 'a kernel-level leash' became"
echo "     'a kernel-level wardyn'. The word 'warden' reads better as a common noun"
echo "     there — reword if you like."
echo "   - if the build errors on OUT_DIR/wardyn, check wardyn-ebpf/Cargo.toml"
echo "     [[bin]] name and the include_bytes path in wardyn/src/main.rs agree."
